#!/usr/bin/fish
echo "Disk Usage <br>"
echo "<table>
<thead>
<tr>
<th>Partition</th>
<th>Used</th>
<th>%</th>
</thead>
<tbody>"
for disk in (df -h | awk -F' ' '{ print $1 }' | sed '/tmpfs/d;/Filesystem/d;/run/d;/^dev/d')
    echo "<tr>
<td>$disk</td>"
    set data (df -h $disk)
    echo "<td>" (echo $data | awk -F' ' '{ print $10 }' | sed -z 's/Used\n//g') "</td>"
    echo "<td>" (echo $data | egrep -o '[0-9]+%') "</td>
</tr>"
end
echo "
</tbody>
</table>
"
echo "Uptime <br>"
echo (uptime) "<br>"
